### ISSUE TITLE
Skips too fast

### ISSUE THREAD

**Issue by DerRockWolf** [squgeim/yt-ad-autoskipper#17]
The extension is skipping the ads too fast. Its because the skip button is in the html but only hidden

**Comment by squgeim** [comment]
Isn't that a feature not a bug?

**Comment by DerRockWolf** [comment]
But shouldn't it skip the ads only if you could physically press the button?

**Comment by ksodari** [comment]
That's what the extension is all about. Saving hassle for you to skip it
manually and in less time. Thus, you can say it's the major feature of this
extension here.

Regards,
Kuber Sodari

**Comment by DerRockWolf** [comment]
Okay...
It is wanted to skip faster then you could manually do then?

**Comment by crokobit** [comment]
Just curious, will this affect the interest of video producer? How youtube decide the ad is affective thus giving video producer money...?

**Comment by DerRockWolf** [comment]
I'm not really sure, but I think that if you skip an ad the producers won't get any money. If this is true, then this extension is somewhat useless...

**Comment by PKCheap** [comment]
It is true that ad slots do not pay out for skipped ads, but I believe the point of this extension is that it still lets through ads that only last for 5-15 seconds, which cannot be skipped. Whereas if you have an ad-blocked, it will not let anything through at all.

**Comment by DerRockWolf** [comment]
@PKCheap good point, but the last time I've got a 5-15 second ad was like a month ago...

**Comment by squgeim** [comment]
I have been rethinking this and I think it makes sense to wait until the button is actually visible as that would mean that the extension is only automating the user's action.

I have implemented this now (#23).

Thank you everyone!

**Comment by DerRockWolf** [comment]
Great news. When will be the new version released?

**Comment by squgeim** [comment]
I am hoping to squeeze in a "don't skip" button in this release. It should be by the end of the weekend.

**Comment by DerRockWolf** [comment]
Nice, thanks for the answer.

**Comment by squgeim** [comment]
This has now been released. I decided not to wait for the dont-skip button.

**Comment by nathaneb** [comment]
I don't understand why wait for the skip button to be visible? It was great when it used to be skip before! We almost didn't have any ads. It was a great feature. 
How do I activate it on my side? 
On behalf of several dozen Parisians who are in favour of the return of the advanced skip !
Cheers, & thanks for your extension ! 
PS : is it working for display on YT too ?

**Comment by PKCheap** [comment]
@nathaneb Because most end users do not understand that just because a button is hidden in your client, does not mean it cannot be triggered. 
Many will see the ad skip way before they would be able to do so manually, and then assume something is broken.

**Comment by squgeim** [comment]
I had two points when I considered implementing this:

1) It was never the intension to block ads. The skip button used to be created only after the timer; but recently YouTube started creating the button as soon the ad starts. The extension only looked for the button's existence so this bug/feature was introduced.

2) I am working on implementing a "do not skip" button. This has been requested many times from the beginning. One of the points of letting the ad play is so that the user can in fact decide to let it play. Even without a do-not-skip button, the user can choose to use the links present to look further into the ad.

**Comment by squgeim** [comment]
I guess the solution here is having user settings. I thing I need to prioritize that over do-not-skip button.

**Comment by squgeim** [comment]
@nathaneb What do you mean by "display on YT"?

**Comment by nathaneb** [comment]
@PKCheap I'm sorry i don't get it. ad auto skipper extension was created to skip the ad, as fast as it can. If the skip button is in the HMTL, good for us. Which users are going to think that something is broken by purposely having an ad skipper extension ? 

 @squgeim 
1) Totally agree, i'm working in adtech so i'm not found of adblock, and can't use it at work. But for me, skipping the ad, when skippable (html or not), is really appreciated. And for your information, it's exactly the same for youtube and the content partner = no revenue. Otherwise, be sure youtube, would never load it in the html before.

2) OK, i'm not really interested in this feature ;) 

display on YT = display ads that you have during the video, often at the bottom of the Youtube player. 

Thanks guys!

**Comment by squgeim** [comment]
@nathaneb You've clearly never gotten this ad: https://www.youtube.com/watch?v=Fkey2ZvX6lU 🤣
I paused the ad to go to the video for the music; and given how many views it has, I was not the only one. 😄
